version: '3.4'

services:
  sharepoint-api:
    image: sousacomz/api-sharepoint:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
