version: '3.8'

services:
  api:
    build:
      context: .
    container_name: api
    expose:
      - "5148"
    environment:
      - ASPNETCORE_URLS=http://+:5148

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
